#getwd()
---
title: "Final_git"
output: html_document
---
#setwd('/Users/shivikakbisen/Desktop/Project_1')
#getwd()
---
title: "Project Report: POMP Model on Foreign Currency Exchange Rate of UK Pound"
date: "4/19/2020"
output:
  html_document:
    fig_caption: true
    theme: flatly
    toc: yes
    toc_depth: 2
    number_sections: true
    pandoc_args: [
      "--number-offset=0"
    ]


# Introduction

--------
```{r libraries, echo=FALSE, warning = FALSE, results = 'hide',message=FALSE}
set.seed(100000)
library(ggplot2)
library(plyr)
library(reshape2)
library(pomp)
library(tseries)
library(doParallel)
library(foreach)
library(doMC)
```

# Data Source

```{r read_data, echo=FALSE,fig.cap="Figure 1. Time Series of Original Data",warning = FALSE}
data = read.csv("https://raw.githubusercontent.com/sbisen/Time-Series-Final-Project/master/rate.csv")
data$Rate = as.numeric(as.character(data$Rate))
# Remove 2790, which is closing market
dt = na.omit(data)
plot(ts(dt$Rate,start = 2000, end = 2020, deltat = 1/260), main="Time Series Plot for GBP/USD from 2000 to 2020",xlab="Year",ylab = 'Exchange Rate',type = 'l')
```

```{r visualize_data, echo=FALSE,fig.cap="Figure 2. Time Series of Used Data"}
# Take the data subset with 400 samples
dt2 = dt[2601:2900,]
dt2$Date=1:300
fx = pomp(dt2,times="Date",t0=0)
fx<- as.data.frame(fx)
plot(fx, xlab = 'time from 0 to 300', main = 'GBP/USD Exchagne Rate')
```


# Mathematical Modal

## Geometric Brownian Motion (GBM) Model

## Parameter Description

* There are 3 parameters $\mu$, $\delta$ and $\sigma$. 

* $\mu$ is the drift parameter that shows the increasing or decreasing trend. 

* $\delta$ is the volatility parameter that measures the deviations from the mean. 

* $\sigma$ is the variance of the state parameter $\epsilon$. By increasing sigma, it will increase the deviations from the mean. 


# POMP Model

## Build POMP Model

* The rprocess is based on the GBM model with two state variables, $N$ and $\epsilon$.

* The parameters are $\mu$, $\sigma$ and $\delta$.

* The initial value of N is drawn from a random poisson distribution with mean 1.5. The initial value of $\epsilon$ is drawn from a poisson distribution with mean 1. 

```{r pomp}
dmeas <- Csnippet("lik = dnorm(Rate,0,N,give_log);")
rmeas <- Csnippet("Rate = rnorm(0,N);")
Ne_initializer <- ("N=rpois(1.5);e=rpois(1);")
stochStep <- Csnippet("
                      e = rnorm(0,sigma);
                      N = N*exp((mu-delta*delta/2)/260+delta/sqrt(260)*e);
                      ")

stopifnot(packageVersion("pomp")>="0.75-1")
fx <- pomp(data = dt2,
     times="Date",
     t0=0,
     rprocess=discrete_time(step.fun=stochStep,delta.t=1),
     rmeasure = rmeas,
     dmeasure=dmeas, 
     obsnames = "Rate",
     paramnames=c("mu","delta","sigma"),
     statenames=c("N","e"),
     #initializer=Csnippet(Ne_initializer)
     rinit=Csnippet(Ne_initializer)
     )
```



```{r run_level}
run_level = 3
level_Np = c(100,1000,5000)
level_Nmif = c(10,100,300)
level_Nreps_eval = c(4,10,20)
level_Nreps_local = c(10,20,20)
level_Nreps_global = c(10,20,100)
```

# Likelihood Slice

 
```{r slicing, echo = FALSE, results = 'hide'}
p <- sliceDesign(
  c(mu=0.1,delta=0.2,sigma=0.4, N=2600),
  mu=rep(seq(from=-10,to=10,length=40),each=3),
  delta=rep(seq(from=0.1,to=3,length=40),each=3),
  sigma=rep(seq(from=0.1,to=3,length=40),each=3)
  )

registerDoMC(cores=5)
set.seed(998468235L,kind="L'Ecuyer")
mcopts <- list(preschedule=FALSE,set.seed=TRUE)

foreach (theta=iter(p,"row"),.combine=rbind,
         .inorder=FALSE,.options.multicore=mcopts) %dopar% 
         {
           pfilter(fx,params=unlist(theta),Np=5000) -> pf
           #pf
           theta$loglik <- logLik(pf)
           theta
         } -> p
```

```{r mu, echo = FALSE, fig.cap="Figure 3. Slicing for mu"}
v = "mu"
x <- subset(p,slice==v)
plot(x[[v]],x$loglik,xlab=v,ylab="loglik",main='slicing for mu')
```

* Along the $\mu$ direction, the slicing for $\mu$ shows that the maximum of log likelihood is located when $\mu$ is aorund 0. 

```{r delta, echo = FALSE, fig.cap="Figure 4. Slicing for delta"}
v = "delta"
x <- subset(p,slice==v)
plot(x[[v]],x$loglik,xlab=v,ylab="loglik",main='slicing for delta')
```

* Along the $\delta$ direction, the slicing for $\delta$ shows that the maximum of log likelihood is located when $\delta$ is around 0.6.

```{r sigma, echo = FALSE, fig.cap="Figure 5. Slicing for sigma"}
v = "sigma"
x <- subset(p,slice==v)
plot(x[[v]],x$loglik,xlab=v,ylab="loglik",main='slicing for sigma')
```

* Along the $\sigma$ direction, the slicing for $\sigma$ shows that the maximum of log likelihood is located when $\sigma$ is 1.3.

-------

-------

# Partical Filter

```{r filtering, echo = FALSE}
test = c(N.0=1.5,e.0=0,mu=0,delta=0.7,sigma=1.4)
registerDoParallel()
stew(file=sprintf("pf1.rda",run_level),{
  t.pf1 <- system.time(
    pf1 <- foreach(i=1:level_Nreps_eval[run_level],.packages='pomp',.options.multicore=list(set.seed=TRUE)) %dopar% try(
                     pfilter(fx,params=test,Np=level_Np[run_level])
                   )
  )
},seed=493536993,kind="L'Ecuyer")
(L_pf <-logmeanexp(sapply(pf1,logLik),se=TRUE))
```

```{r fitting, echo = FALSE}
fx.sd_rp <- 0.002
fx.sd_ivp <- 0.1
fx_cooling.fraction.50 <- 0.1

stew("mif1.rda",{
  t.if1 <- system.time({
    if1 <- foreach(i=1:level_Nreps_local[run_level],
                   .packages='pomp', .combine=c,
                   .options.multicore=list(set.seed=TRUE)) %dopar% try(
                     mif2(fx,
                          start=test,
                          Np=level_Np[run_level],
                          Nmif=level_Nmif[run_level],
                          cooling.type="geometric",
                          cooling.fraction.50=fx_cooling.fraction.50,
                          transform=TRUE,
                          rw.sd = rw.sd(
                            mu = fx.sd_rp,
                            delta = fx.sd_rp,
                            sigma = fx.sd_rp
                          )
                     )
                   )
    
    L.if1 <- foreach(i=1:level_Nreps_local[run_level],.packages='pomp',
                     .combine=rbind,.options.multicore=list(set.seed=TRUE)) %dopar% 
                     {
                       logmeanexp(
                         replicate(level_Nreps_eval[run_level],
                                   logLik(pfilter(fx,params=coef(if1[[i]]),Np=level_Np[run_level]))
                         ),
                         se=TRUE)
                     }
  })
},seed=318817883,kind="L'Ecuyer")
r.if1 <- data.frame(logLik=L.if1[,1],logLik_se=L.if1[,2],t(sapply(if1,coef)))
if (run_level>1) 
  write.table(r.if1,file="fx_params.csv",append=TRUE,col.names=FALSE,row.names=FALSE)
summary(r.if1$logLik,digits=5)
```